# -*- coding: utf-8 -*-
"""Assignment_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s3sV77G6WJa_qqTZQw5s5wRF2EbsQZto

Q1. How do you comment code in Python? What are the different types of comments?
Q2. What are variables in Python? How do you declare and assign values to variables?
Q3. How do you convert one data type to another in Python?
Q4. How do you write and execute a Python script from the command line?
Q5. Given a list my_list = [1, 2, 3, 4, 5], write the code to slice the list and obtain the sub-list [2, 3].
Q6. What is a complex number in mathematics, and how is it represented in Python?
Q7. What is the correct way to declare a variable named age and assign the value 25 to it?
Q8. Declare a variable named price and assign the value 9.99 to it. What data type does this variable
belong to?
Q9. Create a variable named name and assign your full name to it as a string. How would you print the
value of this variable?
Q10. Given the string "Hello, World!", extract the substring "World".
Q11. Create a variable named "is_student" and assign it a boolean value indicating whether you are
currently a student or not.
"""

# Q1. How do you comment code in Python? What are the different types of comments?
# Single-line comment example
x = 10  # This is an inline comment

"""
This is a multi-line comment
(using triple double-quotes)
"""

'''
This is also a multi-line comment
(using triple single-quotes)
'''

# Q2. What are variables in Python? How do you declare and assign values to variables?
# Variable declaration and assignment
x = 5        # Integer
y = 3.14     # Float
name = "John" # String
is_active = True # Boolean

print(x, y, name, is_active)

# Q3. How do you convert one data type to another in Python?
a = 10
b = 3.5
c = "20"

# Type conversion
int_to_float = float(a)
float_to_int = int(b)
str_to_int = int(c)

print(int_to_float, float_to_int, str_to_int)

# Q4. How do you write and execute a Python script from the command line?
print("Hello, World!")
# Open command line and navigate to the file location.
# python script.py

# Q5. Slice my_list to get [2, 3]
my_list = [1, 2, 3, 4, 5]
sub_list = my_list[1:3]  # Slicing from index 1 to 2
print(sub_list)

# Q6. What is a complex number in mathematics, and how is it represented in Python?
z = 3 + 4j
print(z, type(z))

# Q7. Correct way to declare a variable named age and assign 25 to it
age = 25
print(age)

# Q8. Declare a variable price with value 9.99 and check its type
price = 9.99
print(type(price))  # Output: <class 'float'>

# Q9. Declare a variable name and print its value
name = "Omkar Patil"
print(name)

# Q10. Extract substring "World" from "Hello, World!"
text = "Hello, World!"
substring = text[7:12]  # Extract characters from index 7 to 11
print(substring)

# Q11. Create a variable is_student and assign a boolean value
is_student = False  # Change to True if you are a student
print(is_student)

