# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XWK3Gv5ZR1pcOhZhdn2xj5F51iVnoQ4L
"""

# Q1. Create one variable containing following type of data:
# (i) string
# (ii) list
# (iii) float
# (iv) tuple


# Q2. Given are some following variables containing data:
# (i) var1 = ‘ ‘
# (ii) var2 = ‘[ DS , ML , Python]’
# (iii) var3 = [ ‘DS’ , ’ML’ , ‘Python’ ]
# (iv) var4 = 1.


# What will be the data type of the above given variable.


# Q3. Explain the use of the following operators using an example:
# (i) /
# (ii) %
# (iii) //
# (iv) **

# Q4. Create a list of length 10 of your choice containing multiple types of data. Using for loop print the element and its data type.

# Q5. Using a while loop, verify if the number A is purely divisible by number B and if so then how many times it can be divisible.

# Q6. Create a list containing 25 int type data. Using for loop and if-else condition print if the element is divisible by 3 or not.

# Q7. What do you understand about mutable and immutable data types? Give examples for both showing this property.

# Q1. Create one variable containing multiple data types
var = ("Hello", [1, 2, 3], 3.14, (4, 5, 6))
print(var)

# Q2. Data types of given variables
var1 = ' '            # str
var2 = '[ DS , ML , Python]'  # str
var3 = ['DS', 'ML', 'Python']  # list
var4 = 1.            # float

print(type(var1))
print(type(var2))
print(type(var3))
print(type(var4))

# Q3. Operators Explanation
# (i) Division /
print(10 / 3)  # Output: 3.3333

# (ii) Modulus %
print(10 % 3)  # Output: 1 (Remainder)

# (iii) Floor Division //
print(10 // 3)  # Output: 3 (Quotient without decimal)

# (iv) Exponentiation **
print(2 ** 3)  # Output: 8 (2^3)

# Q4. List of 10 elements with different data types
my_list = [10, 3.14, "Python", True, [1, 2], (3, 4), {5, 6}, {"key": "value"}, None, complex(2, 3)]

for item in my_list:
    print(f"Element: {item}, Type: {type(item)}")

# Q5. Check divisibility using while loop
A = 100
B = 5
count = 0

while A % B == 0:
    A = A // B
    count += 1

print(f"Number is divisible {count} times.")

# Q6. List of 25 integers & check divisibility by 3
num_list = list(range(1, 26))

for num in num_list:
    if num % 3 == 0:
        print(f"{num} is divisible by 3")
    else:
        print(f"{num} is not divisible by 3")

# Q7. Mutable vs Immutable Data Types
# Mutable Example (List)
mutable_list = [1, 2, 3]
mutable_list[0] = 100  # List can be changed
print(mutable_list)

# Immutable Example (Tuple)
immutable_tuple = (1, 2, 3)
# immutable_tuple[0] = 100  # This will raise an error because tuples cannot be modified
print(immutable_tuple)

